### ISSUE TITLE
A new miss string

### ISSUE THREAD

**Issue by Mapaler** [puzzled-dragon/pad-helper#8]
![screenshot_20180924-222129](https://user-images.githubusercontent.com/6565860/46191543-860f6a00-c32a-11e8-9d8d-e50d38d228ce.jpg)

**Comment by puzzled-dragon** [comment]
Hi !
Thanks for reporting this.

Please see commit 1cd3b14708225d0205447584f915560aa062eb09

**Comment by Mapaler** [comment]
![pixlr_20181004121608585](https://user-images.githubusercontent.com/6565860/46452674-919ddd80-c7cf-11e8-9c2b-153b78106901.jpg)
A new string and the info is under the manual mode on my Sony XZs(Android 8.0).So it is not easy to check. Actually, I'm saw it on my Nexus 5(Android 6.0), at this phone info is over the manual mode.

**Comment by puzzled-dragon** [comment]
Hey !
Thanks again (See commit 57aef33bbcba0a11e39664c933c0913a5837eb38 for changes).

Also, I see you noticed that the "Toast" (= the small gray area where the message is displayed) is underneath the manual mode.
Unfortunately, I can't fix it easily (Toast is standard Android library, and I couldn't get it to appear above the manual mode view).
And it is always under unfortunately. In the second screenshot, it appears to be over, but it is because the bottom half on the manual mode is transparent (see the checkbox state).

**Comment by Mapaler** [comment]
![pic](https://user-images.githubusercontent.com/6565860/46590886-64ac3c00-cae9-11e8-87d2-8e37395e875f.jpg)
I don't know why, but it doesn't appear the same on different phones.
